### ISSUE TITLE
Flipped accelerometer axis in the HARTH dataset

### ISSUE THREAD

**Issue by claaslendt** [ntnu-ai-lab/harth-ml-experiments#2]
Hi,

I just want to note that the y- and z-axis for the thigh-accelerometer data in the HARTH dataset are flipped for all participants with an ID > 22 (i.e. S023.csv and upwards). I assume this is due to the orientation of the AX3 sensor in the second session, which would correspond to the number of participants where this is the case (n = 7).

For example, this can easily be inspected visually for the z-axis when plotting a sequence labelled as sitting or lying:

![grafik](https://github.com/user-attachments/assets/1ab71432-3581-48e4-9479-d7f05febdf55)

![grafik](https://github.com/user-attachments/assets/6021685b-5884-4ded-b971-de82c5fafa28)

**Comment by alogacjov** [comment]
Hi,

Thank you very much for pointing this out. We checked the data and the thigh sensor is indeed rotated around the x-axis, thereby flipping the sign of the y and z axes recordings. However, this is the case for subjects 6-22 not to the others. The z-axis supposed to point down during sitting, which should lead to a negative acceleration, which is correct for subjects >22 but not <=22. We changed that now by applying a corresponding rotation matrix to the thigh sensor, rotating the axes around the x axis by 180 degrees, which basically just changes the y and z signs.

Thanks again for letting us know.
